version: "3"

server:
  command: "php worker.php"
  relay: pipes

http:
  address: "0.0.0.0:8080"
  middleware:
    - gzip
    - headers
  headers:
    response:
      X-Powered-By: "RoadRunner"
  pool:
    num_workers: 0
    max_jobs: 500
    allocate_timeout: 60s
    destroy_timeout: 60s

metrics:
  address: "0.0.0.0:2112"

status:
  address: "0.0.0.0:2114"

logs:
  mode: production
  level: info
  encoding: json
  output: stderr
